### ISSUE TITLE
复杂和普通缓存数据如何清除

### ISSUE THREAD

**Issue by cyfei211** [angejia/pea#15]
目前update只清除简单缓存数据，然后更新表版本，而没有清除对应的产生的复杂和普通缓存数据，这样导致下次复杂和普通查询时会根据新的版本号生成新的缓存，旧缓存永远不会被用到而且没有被清除，这样会导致redis里的数据越来越多，请问如何解决 @lvht 请问你们是怎么处理垃圾缓存数据的

**Comment by taoso** [comment]
redis开启lru缓存策略就可以了。redis会动态删除老旧的缓存数据。

因为一张表可能有非常多的复杂查询。如果在更新数据的时候主动删除这些缓存，成本会比较高。这也是引入表版本的原因。

**Comment by cyfei211** [comment]
非常感谢，这个思路非常棒，可以问下你们公司的maxmemory-policy值设置的是allkeys-lru吗
