### ISSUE TITLE
表没有主键改如何处理？

### ISSUE THREAD

**Issue by lvht** [angejia/pea#4]

**Comment by lvht** [comment]
对于没有主键的表，无法使用行级缓存。表级缓存不受影响。如果针对这种表开启了缓存而且执行了**普通查询**的话，系统会执行转换后的**简单查询**，最终导致报错。

所以，目前的解决方法有二：
- 强制所有的表设置主键，没有的添加自增主键
- 不要对没有主键的模型开启缓存

**Comment by lvht** [comment]
@lrgoodboy @imaben

**Comment by lrgoodboy** [comment]
@lvht 最终定了哪个？

**Comment by lvht** [comment]
默认不开启缓存。
